#!/usr/bin/expect -f

puts "\r ** START FINGERPRINTING ON CLIENT DEVICE ** \r\n"

set number_of_fingerprints_to_be_made [lindex $argv 0]

# Activate the Conda environment within Expect
spawn bash 
send "source ~/anaconda3/bin/activate py27\r"
expect "$ "

# start tick console
send "python /home/patrik/BA/thetick/tick.py \r"
expect "$ "


# wait until bot has connected
set timeout 30
expect {
    -re {Bot [0-9]+ \[[^\]]+\] connected from [0-9.]+} {
        puts "\r✅ Bot connected.\r"
    }
    timeout {
        puts "\r❌ Timeout waiting for bot connection.\r"
        exit 1
    }
}
sleep 5


# select bot 0 to work with
send "use 0\r"
expect "$ "

# starts interactive shell inside tick console
send "shell\r"	
sleep 5


# start fingerprinting in screen on client device, makes sure the script stays running after leaving the shell
set fingerprinting_shell_script_location "/home/admin/BA/fingerprinting/fingerprinter.sh"
send "sudo screen -dmS fingerprinting bash $fingerprinting_shell_script_location -n $number_of_fingerprints_to_be_made\r"
sleep 5
puts "\rfingerprinting started\r"

